import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { KpiCard } from '../components/KpiCard';
import * as signalR from '@microsoft/signalr';

export default function Dashboard(){
  const [data,setData]=useState<any>(null);
  const [insight,setInsight]=useState<string>('');
  const [loading,setLoading]=useState(true);
  const [live,setLive]=useState(false);

  async function load(){
    const [k,r]=await Promise.all([api.get('/dashboard/kpis'), api.get('/dashboard/insight').catch(()=>({data:{insight:'Insight unavailable offline'}}))]);
    setData(k.data); setInsight(r.data.insight); setLoading(false);
  }
  useEffect(()=>{ load(); },[]);

  useEffect(()=>{
    const token = localStorage.getItem('token');
    const conn = new signalR.HubConnectionBuilder()
      .withUrl(((import.meta as any).env?.VITE_API_URL||'http://localhost:5000')+'/hubs/dashboard', { accessTokenFactory:()=> token||'' })
      .withAutomaticReconnect()
      .build();
    conn.on('KpiUpdated', (payload)=>{ console.log('live',payload); setLive(true); setTimeout(()=>setLive(false),3000); load(); });
    conn.start().then(()=>conn.invoke('SubscribeToKpis')).catch(()=>{});
    return ()=>{ conn.stop(); };
  },[]);

  if(loading) return <div className="text-sm text-slate-500">Loading command center…</div>;
  const d=data;
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div><h1 className="text-2xl font-bold">Command Center</h1><p className="text-sm text-slate-500">Live KPIs via SignalR • AI Insight Panel answers “What changed? Why? What needs attention?”</p></div>
        <div className="flex items-center gap-2">{live && <span className="px-2 py-1 bg-green-500 text-white text-xs rounded animate-pulse">● LIVE UPDATE</span>}<span className="text-xs text-slate-500">{new Date(d.generatedAt).toLocaleString('en-IN')}</span></div>
      </div>

      {/* Row 1 - core ops */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <KpiCard label="Beds Occupied" value={`${d.bedsOccupied}/${d.bedsTotal}`} sub={`${d.occupancyPct}% occupancy`} delta={2.1} color="blue" />
        <KpiCard label="OPD Today" value={d.opdToday} unit="visits" sub="120–160 target" delta={5.4} />
        <KpiCard label="Admissions / Discharges" value={`${d.admissionsToday} / ${d.dischargesToday}`} sub={`Avg LOS ${d.avgLos} days`} />
        <KpiCard label="Revenue Today" value={`₹${(d.revenueToday/100000).toFixed(1)}L`} unit="INR" sub="₹1.8cr/mo target" delta={-1.2} color="green" />
      </div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <KpiCard label="Recoverable Leakage" value={`₹${(d.leakageAlerts* 8500/1000).toFixed(0)}K`} sub={`${d.leakageAlerts} alerts • ₹1–2L/mo target`} color="red" />
        <KpiCard label="Outstanding Claims" value={`₹${(d.outstandingClaims/100000).toFixed(1)}L`} sub={`${d.rejectionRate}% rejection`} delta={d.rejectionRate-12} color={d.rejectionRate>12?'red':'green'} />
        <KpiCard label="Expiry Alerts" value={d.expiryAlerts} sub="90-day window" color={d.expiryAlerts>2?'amber':'slate'} />
        <KpiCard label="Readmissions" value="2" unit="this week" sub="target <5%" />
      </div>

      {/* AI Insight Panel */}
      <div className="bg-gradient-to-br from-blue-600 to-indigo-700 rounded-xl p-5 text-white shadow">
        <div className="text-xs font-bold tracking-widest opacity-80">AI INSIGHT PANEL — DAILY SUMMARY (not patient-identifiable)</div>
        <div className="mt-2 text-sm leading-relaxed whitespace-pre-wrap">{insight}</div>
        <div className="mt-3 text-xs opacity-70">Generated by IAiClient from aggregated KPI deltas • Model: stub-model v1 • Human review not required for aggregate insight</div>
      </div>

      {/* KPI snapshots */}
      <div className="bg-white rounded-xl border p-4">
        <div className="text-sm font-semibold">KPI Snapshots</div>
        <div className="mt-3 grid md:grid-cols-2 gap-2">
          {(d.kpis||[]).map((k:any)=>
            <div key={k.metricName} className="flex items-center justify-between border rounded-lg px-3 py-2">
              <span className="text-sm">{k.metricName} <span className="text-xs text-slate-500">{k.category}</span></span>
              <span className="font-bold">{k.value}{k.unit==='%'?'%':k.unit==='INR'?'':' '+k.unit} {k.deltaPercent!=null && <span className={`text-xs ${k.deltaPercent>0?'text-green-600':'text-red-600'}`}>{k.deltaPercent>0?'+':''}{k.deltaPercent.toFixed(1)}%</span>}</span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
